/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import OSPABA.ISimDelegate;
import OSPABA.SimState;
import OSPABA.Simulation;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import simulation.MySimulation;
import zamestnanci.Kadernicka;
import zamestnanci.Kozmeticka;
import zamestnanci.Recepcna;

/**
 *
 * @author Jožko
 */
public class SimulacneOkno extends javax.swing.JFrame implements ISimDelegate {

    DefaultTableModel model;  
    boolean pauza = false;
    boolean koniec = false;
    MySimulation salon;
    
    /**
     * Creates new form SimulacneOkno
     */
    public SimulacneOkno() {
        initComponents();   
        model = (DefaultTableModel) tabulkaRecepcnych.getModel();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pocetRecepcnych = new javax.swing.JTextField();
        pocetKadernicok = new javax.swing.JTextField();
        pocetKozmeticok = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabulkaRecepcnych = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabulkaKadernicok = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabulkaKozmeticok = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        recepcneRadStatistiky = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        kadernickyRadStatistiky = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        kozmetickyRadStatistiky = new javax.swing.JTable();
        spojitostSimulacie = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        pauzaTlac = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ineStatistiky = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        pocetParkovacichRadov = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 700));

        jLabel1.setText("R:");

        jLabel2.setText("Kad:");

        jLabel3.setText("Koz:");

        jButton1.setText("Štart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Recepčné:");

        tabulkaRecepcnych.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Recepčná", "Stav", "Vyťaženie", "Vyťaženie bez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabulkaRecepcnych);

        jLabel5.setText("Kaderníčky:");

        tabulkaKadernicok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kaderníčka", "Stav", "Vyťaženie", "Vyťaženie bez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabulkaKadernicok);

        jLabel6.setText("Kozmetičky:");

        tabulkaKozmeticok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kozmetička", "Stav", "Vyťaženie", "Vyťaženie bez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabulkaKozmeticok);

        recepcneRadStatistiky.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aktuálna dĺžka radu - objednávky", "0", null},
                {"Priemerný čas v rade - objednávky", "0", null},
                {"Priemerná dĺžka radu - objednávky", "0", null},
                {"Aktuálna dĺžka radu - platby", "0", null},
                {"Priemerný čas v rade - platby", "0", null},
                {"Priemerná dĺžka radu - platby", "0", null},
                {"Priemerný čas obsluhy", "0", null}
            },
            new String [] {
                "Štatistika", "Hodnota", "Hodnota bez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(recepcneRadStatistiky);

        kadernickyRadStatistiky.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aktuálna dĺžka radu", "0", null},
                {"Priemerný čas v rade", "0", null},
                {"Priemerná dĺžka radu", "0", null},
                {"Priemerný čas obsluhy", "0", null}
            },
            new String [] {
                "Štatistika", "Hodnota", "Hodnota bez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(kadernickyRadStatistiky);

        kozmetickyRadStatistiky.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aktuálna dĺžka radu", "0", null},
                {"Priemerný čas čakania na čistenie", "0", null},
                {"Priemerná dĺžka radu", "0", null},
                {"Priemerný čas obsluhy", "0", null}
            },
            new String [] {
                "Štatistika", "Hodnota", "Hodnota bez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(kozmetickyRadStatistiky);

        spojitostSimulacie.setMaximum(400);
        spojitostSimulacie.setMinimum(25);
        spojitostSimulacie.setValue(100);

        jLabel9.setText("Rých:");

        pauzaTlac.setText("Pauza");
        pauzaTlac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauzaTlacActionPerformed(evt);
            }
        });

        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        jLabel12.setText("Recepčné rady:");

        jLabel13.setText("Kaderníčky rad:");

        jLabel14.setText("Kozmetičky rad:");

        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ineStatistiky.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Simulačný čas", "00:00:00", null},
                {"Otvorené naviac", "00:00:00", null},
                {"Počet ľudí - prišlo pešo", "0", "0"},
                {"Počet ľudí odišlo", "0", "0"},
                {"Čas v systéme", "00:00:00", "00:00:00"},
                {"Počet ľudí vyhodených", "0", null},
                {"Spokojnosť", "0", null},
                {"Úspešnosť parkovania", "0", null},
                {"Počet ľudí - prišlo autom", "0", "0"}
            },
            new String [] {
                "Štatistika", "Hodnota", "Hodnota bez"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ineStatistiky);

        jLabel7.setText("Park:");

        jButton3.setText("Zmeň rýchlosť");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pocetRecepcnych, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pocetKadernicok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pocetKozmeticok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pocetParkovacichRadov, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pauzaTlac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spojitostSimulacie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70)
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pocetRecepcnych, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pocetKadernicok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pocetKozmeticok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jButton1)
                        .addComponent(jLabel9)
                        .addComponent(pauzaTlac)
                        .addComponent(stop)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pocetParkovacichRadov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spojitostSimulacie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jButton3)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        salon = new MySimulation(Integer.parseInt(pocetRecepcnych.getText()), Integer.parseInt(pocetKadernicok.getText()), Integer.parseInt(pocetKozmeticok.getText()), Integer.parseInt(pocetParkovacichRadov.getText()));
        ZoznamZakaznikov zz = new ZoznamZakaznikov();
        zz.setVisible(true);
        salon.registerDelegate(this);
        salon.registerDelegate(zz);
        salon.setSimSpeed(1, 1);
        salon.simulateAsync(1);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pauzaTlacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauzaTlacActionPerformed
        if (pauza == false) {
            pauza = true;
            pauzaTlac.setText("Ďalej");
            salon.pauseSimulation();
        } else {
            pauza = false;
            pauzaTlac.setText("Pauza");
            salon.resumeSimulation();
        }
    }//GEN-LAST:event_pauzaTlacActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        salon.stopSimulation();
    }//GEN-LAST:event_stopActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Menu().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double kolko = spojitostSimulacie.getValue() / 100;
        salon.setSimSpeed(1, kolko);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulacneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulacneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulacneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulacneOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulacneOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ineStatistiky;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable kadernickyRadStatistiky;
    private javax.swing.JTable kozmetickyRadStatistiky;
    private javax.swing.JButton pauzaTlac;
    private javax.swing.JTextField pocetKadernicok;
    private javax.swing.JTextField pocetKozmeticok;
    private javax.swing.JTextField pocetParkovacichRadov;
    private javax.swing.JTextField pocetRecepcnych;
    private javax.swing.JTable recepcneRadStatistiky;
    private javax.swing.JSlider spojitostSimulacie;
    private javax.swing.JButton stop;
    private javax.swing.JTable tabulkaKadernicok;
    private javax.swing.JTable tabulkaKozmeticok;
    private javax.swing.JTable tabulkaRecepcnych;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh(Simulation simulacia) {       
        // model tabulky recepcne - vypis
        DefaultTableModel modelRec = (DefaultTableModel) tabulkaRecepcnych.getModel();
        
        // model tabulky kadernicky - vypis
        DefaultTableModel modelKad = (DefaultTableModel) tabulkaKadernicok.getModel();
        
        // model tabulky kozmeticky - vypis
        DefaultTableModel modelKoz = (DefaultTableModel) tabulkaKozmeticok.getModel();
         
        // aktualizacia hodnot v tabulke recepcnych
        if (modelRec.getRowCount() > 0) { // ak je uz tabulka naplnena, len aktualizuj stavy personalu
            for (int i = 0; i < ((MySimulation) simulacia).agentRecepcnych().dajZoznamVsetkychRecepcnychVypis().size(); i++) {
                String data2 = "nepracuje";
                if (((MySimulation) simulacia).agentRecepcnych().dajZoznamVsetkychRecepcnychVypis().get(i).dajStavPracovania()) {
                    data2 = "pracuje";
                }
                // aktualizacia stavu (pracuje, nepracuje)
                modelRec.setValueAt(data2, i, 1);
                // aktualizacia aktualnej hodnoty vytazenia pracovnicky
                modelRec.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentRecepcnych().dajZoznamVsetkychRecepcnychVypis().get(i).vypocitajVytazenie(((MySimulation) simulacia).currentTime())) + "%", i, 2);
                if (((MySimulation) simulacia).currentTime() < 28800) {
                    modelRec.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentRecepcnych().dajZoznamVsetkychRecepcnychVypis().get(i).vypocitajVytazenie(((MySimulation) simulacia).currentTime())) + "%", i, 3);
                }
            }
        } else { // ak je tabulka nenaplnena, tak ju napln personalom
            for (Recepcna recepcna : ((MySimulation) simulacia).agentRecepcnych().dajZoznamVsetkychRecepcnychVypis()) {
                String idRec = String.valueOf(recepcna.dajID());
                String stavRec = "nepracuje";
                if (recepcna.dajStavPracovania()) {
                    stavRec = "pracuje";
                }
                String vytazenieRec = "0%";
                Object[] row = {idRec, stavRec, vytazenieRec, vytazenieRec};
                modelRec.addRow(row);
            }
        }
        
        // aktualizacia hodnot v tabulke kadernicok       
        if (modelKad.getRowCount() > 0) { // ak je uz tabulka naplnena, len aktualizuj stavy personalu
            for (int i = 0; i < ((MySimulation) simulacia).agentKadernicok().dajZoznamVsetkychKadernicokVypis().size(); i++) {
                String data2 = "nepracuje";
                if (((MySimulation) simulacia).agentKadernicok().dajZoznamVsetkychKadernicokVypis().get(i).dajStavPracovania()) {
                    data2 = "pracuje";
                }
                // aktualizacia stavu (pracuje, nepracuje)
                modelKad.setValueAt(data2, i, 1);
                // aktualizacia aktualnej hodnoty vytazenia pracovnicky
                modelKad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentKadernicok().dajZoznamVsetkychKadernicokVypis().get(i).vypocitajVytazenie(((MySimulation) simulacia).currentTime())) + "%", i, 2);
                if (((MySimulation) simulacia).currentTime() < 28800) {
                    modelKad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentKadernicok().dajZoznamVsetkychKadernicokVypis().get(i).vypocitajVytazenie(((MySimulation) simulacia).currentTime())) + "%", i, 3);
                }
            }
        } else { // ak je tabulka nenaplnena, tak ju napln personalom
            for (Kadernicka kadernicka : ((MySimulation) simulacia).agentKadernicok().dajZoznamVsetkychKadernicokVypis()) {
                String idRec = String.valueOf(kadernicka.dajID());
                String stavRec = "nepracuje";
                if (kadernicka.dajStavPracovania()) {
                    stavRec = "pracuje";
                }
                String vytazenieKad = "0%";
                Object[] row = {idRec, stavRec, vytazenieKad, vytazenieKad};
                modelKad.addRow(row);
            }
        }
        
        
        // aktualizacia hodnot v tabulke kozmeticok
        if (modelKoz.getRowCount() > 0) { // ak je uz tabulka naplnena, len aktualizuj stavy personalu
            for (int i = 0; i < ((MySimulation) simulacia).agentKozmeticok().dajZoznamVsetkychKozmeticokVypis().size(); i++) {
                String data2 = "nepracuje";
                if (((MySimulation) simulacia).agentKozmeticok().dajZoznamVsetkychKozmeticokVypis().get(i).dajStavPracovania()) {
                    data2 = "pracuje";
                }
                // aktualizacia stavu (pracuje, nepracuje)
                modelKoz.setValueAt(data2, i, 1);
                // aktualizacia aktualnej hodnoty vytazenia pracovnicky
                modelKoz.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentKozmeticok().dajZoznamVsetkychKozmeticokVypis().get(i).vypocitajVytazenie(((MySimulation) simulacia).currentTime())) + "%", i, 2);
                if (((MySimulation) simulacia).currentTime() < 28800) {
                    modelKoz.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentKozmeticok().dajZoznamVsetkychKozmeticokVypis().get(i).vypocitajVytazenie(((MySimulation) simulacia).currentTime())) + "%", i, 3);
                }
            }
        } else { // ak je tabulka nenaplnena, tak ju napln personalom
            for (Kozmeticka kozmeticka : ((MySimulation) simulacia).agentKozmeticok().dajZoznamVsetkychKozmeticokVypis()) {
                String idRec = String.valueOf(kozmeticka.dajID());
                String stavRec = "nepracuje";
                if (kozmeticka.dajStavPracovania()) {
                    stavRec = "pracuje";
                }
                String vytazenieKoz = "0%";
                Object[] row = {idRec, stavRec, vytazenieKoz, vytazenieKoz};
                modelKoz.addRow(row);
            }
        }
              
        // model tabulky - statistiky radu - recepcne
        DefaultTableModel modelRecRad = (DefaultTableModel) recepcneRadStatistiky.getModel();
        
        // model tabulky - statistiky radu - kadernicky
        DefaultTableModel modelKadRad = (DefaultTableModel) kadernickyRadStatistiky.getModel();
        
        // model tabulky - statistiky radu - kozmeticky
        DefaultTableModel modelKozRad = (DefaultTableModel) kozmetickyRadStatistiky.getModel();
        
        // aktualizacia aktualnej dlzky radu pred recepcnymi - objednavka
        modelRecRad.setValueAt(((MySimulation) simulacia).agentRecepcnych().dajRadZakaznikovPredRecepcnymiObjednavka().size(), 0, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelRecRad.setValueAt(((MySimulation) simulacia).agentRecepcnych().dajRadZakaznikovPredRecepcnymiObjednavka().size(), 0, 2);
        }
        
        
        // aktualizacia aktualnej dlzky radu pred recepcnymi - platba
        modelRecRad.setValueAt(((MySimulation) simulacia).agentRecepcnych().dajRadZakaznikovPredRecepcnymiPlatba().size(), 3, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelRecRad.setValueAt(((MySimulation) simulacia).agentRecepcnych().dajRadZakaznikovPredRecepcnymiPlatba().size(), 3, 2);
        }
        
        
        // aktualizacia priemernej dlzky radu pred recepcnymi - objednavka
        modelRecRad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentRecepcnych().dajStatistikuDlzkaRadRecepcneObjednavka().dajPriemernuDlzkuRadu(((MySimulation) simulacia).currentTime())), 2, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelRecRad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentRecepcnych().dajStatistikuDlzkaRadRecepcneObjednavka().dajPriemernuDlzkuRadu(((MySimulation) simulacia).currentTime())), 2, 2);
        }
        
        
        // aktualizacia priemernej dlzky radu pred recepcnymi - platba
        modelRecRad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentRecepcnych().dajStatistikuDlzkaRadRecepcnePlatba().dajPriemernuDlzkuRadu(((MySimulation) simulacia).currentTime())), 5, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelRecRad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentRecepcnych().dajStatistikuDlzkaRadRecepcnePlatba().dajPriemernuDlzkuRadu(((MySimulation) simulacia).currentTime())), 5, 2);
        }
        
        
        // aktualizacia priemerneho casu v rade pred recepcnymi - objednavka
        modelRecRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentRecepcnych().dajStatistikuRadRecepcneObjednavka().dajPriemer()), 1, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelRecRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentRecepcnych().dajStatistikuRadRecepcneObjednavka().dajPriemer()), 1, 2);
        }
        
        
        // aktualizacia priemerneho casu v rade pred recepcnymi - platba
        modelRecRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentRecepcnych().dajStatistikuRadRecepcnePlatba().dajPriemer()), 4, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelRecRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentRecepcnych().dajStatistikuRadRecepcnePlatba().dajPriemer()), 4, 2);
        }
        
        
        // aktualizacia priemernej doby obsluhy recepcnymi
        modelRecRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentRecepcnych().dajStatistikuDobaObsluhyRecepcne().dajPriemer()), 6, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelRecRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentRecepcnych().dajStatistikuDobaObsluhyRecepcne().dajPriemer()), 6, 2);
        }       
        
        // aktualizacia aktualnej dlzky radu pred kadernickami
        modelKadRad.setValueAt(((MySimulation) simulacia).agentKadernicok().dajRadZakaznikovPredKadernickami().size(), 0, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelKadRad.setValueAt(((MySimulation) simulacia).agentKadernicok().dajRadZakaznikovPredKadernickami().size(), 0, 2);
        }
        
        
        // aktualizacia priemerneho casu v rade pred kadernickami
        modelKadRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentKadernicok().dajStatistikuRadKadernicky().dajPriemer()), 1, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelKadRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentKadernicok().dajStatistikuRadKadernicky().dajPriemer()), 1, 2);
        }
        
        
        // aktualizacia priemernej dlzky radu pred kadernickami
        modelKadRad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentKadernicok().dajStatistikuDlzkaRadKadernicky().dajPriemernuDlzkuRadu(((MySimulation) simulacia).currentTime())), 2, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelKadRad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentKadernicok().dajStatistikuDlzkaRadKadernicky().dajPriemernuDlzkuRadu(((MySimulation) simulacia).currentTime())), 2, 2);
        }
        
        
        // aktualizacia priemernej doby obsluhy kadernickami
        modelKadRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentKadernicok().dajStatistikuDobaObsluhyKadernicky().dajPriemer()), 3, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelKadRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentKadernicok().dajStatistikuDobaObsluhyKadernicky().dajPriemer()), 3, 2);
        }
        
        
        // aktualizacia aktualnej dlzky radu pred kozmetickami
        modelKozRad.setValueAt(((MySimulation) simulacia).agentKozmeticok().dajRadZakaznikovPredKozmetickami().size(), 0, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelKozRad.setValueAt(((MySimulation) simulacia).agentKozmeticok().dajRadZakaznikovPredKozmetickami().size(), 0, 2);
        }
        
        
        // aktualizacia priemerneho casu v rade pred kozmetickami
        modelKozRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentKozmeticok().dajStatistikuRadKozmeticky().dajPriemer()), 1, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelKozRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentKozmeticok().dajStatistikuRadKozmeticky().dajPriemer()), 1, 2);
        }
                
        // aktualizacia priemernej dlzky radu pred kozmetickami
        modelKozRad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentKozmeticok().dajStatistikuDlzkaRadKozmeticky().dajPriemernuDlzkuRadu(((MySimulation) simulacia).currentTime())), 2, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelKozRad.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentKozmeticok().dajStatistikuDlzkaRadKozmeticky().dajPriemernuDlzkuRadu(((MySimulation) simulacia).currentTime())), 2, 2);
        }
        
        // aktualizacia priemernej doby obsluhy kozmetickami
        modelKozRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentKozmeticok().dajStatistikuDobaObsluhyKozmeticky().dajPriemer()), 3, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelKozRad.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentKozmeticok().dajStatistikuDobaObsluhyKozmeticky().dajPriemer()), 3, 2);
        }
              
        // model tabulky - statistiky radu - kozmeticky
        DefaultTableModel modelIne = (DefaultTableModel) ineStatistiky.getModel();
        
        // aktualizacia aktualneho simulacneho casu
        modelIne.setValueAt(((MySimulation) simulacia).agentModelu().dajFormatovanySimulacnyCas(), 0, 1);
        
        // ako dlho bolo otvorene po - aktualizacia hodnoty
        if (((MySimulation) simulacia).currentTime() >= 28800) {
            modelIne.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentSalonu().kolkoJeOtvoreneNaviac(((MySimulation) simulacia).currentTime())), 1, 1);
        }
        
        // aktualizacia priemerneho casu zakaznika v modeli
        modelIne.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentOkolia().dajStatistikuCasVSysteme().dajPriemer()), 4, 1);     
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelIne.setValueAt(((MySimulation) simulacia).agentSalonu().dajFormatovanySimulacnyCas(((MySimulation) simulacia).agentOkolia().dajStatistikuCasVSysteme().dajPriemer()), 4, 2);
        }
        
        // aktualizacia poctu ludi, ktori prisli do systemu - peso    
        modelIne.setValueAt(((MySimulation) simulacia).agentOkolia().dajPocetLudiKtoriPrisliDoSalonuPeso(), 2, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelIne.setValueAt(((MySimulation) simulacia).agentOkolia().dajPocetLudiKtoriPrisliDoSalonuPeso(), 2, 2);
        }
        
        // aktualizacia poctu ludi, ktori prisli do systemu - autom     
        modelIne.setValueAt(((MySimulation) simulacia).agentOkolia().dajPocetLudiKtoriPrisliDoSalonuAutom(), 8, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelIne.setValueAt(((MySimulation) simulacia).agentOkolia().dajPocetLudiKtoriPrisliDoSalonuAutom(), 8, 2);
        }
        
        // aktualizacia poctu ludi, ktori odisli zo systemu
        modelIne.setValueAt(((MySimulation) simulacia).agentOkolia().dajPocetLudiKtoriOdisliZoSalonu(), 3, 1);
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelIne.setValueAt(((MySimulation) simulacia).agentOkolia().dajPocetLudiKtoriOdisliZoSalonu(), 3, 2);
        }
        
        // aktualizacia poctu ludi muselo odist z radu pred recepcnymi
        if (((MySimulation) simulacia).currentTime() >= 28800) {
            modelIne.setValueAt((int)((MySimulation) simulacia).agentRecepcnych().dajKolkoLudiSomPoslalPrec(), 5, 1);
        }
        
        // aktualizacia spokojnosti
        if (((MySimulation) simulacia).currentTime() < 28800) {
            modelIne.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentParkovania().dajStatistikuSpokojnost().dajPriemer()), 6, 1);
        }
        
        // aktualizacia uspesnosti parkovania
        if (((MySimulation) simulacia).currentTime() < 28800 && ((MySimulation) simulacia).agentOkolia().dajPocetLudiKtoriPrisliDoSalonuPeso() > 0) {
            modelIne.setValueAt(String.format("%.2f", ((MySimulation) simulacia).agentParkovania().dajKolkoAutUspesneZaparkovalo() / (double)((MySimulation) simulacia).agentOkolia().dajPocetLudiKtoriPrisliDoSalonuAutom() * 100), 7, 1);
        }
    }

    @Override
    public void simStateChanged(Simulation smltn, SimState ss) {
        switch (ss)
		{
		case running:
			
		break;
			
		case replicationRunning:
			// noop
		break;

		case replicationStopped:
			// noop
		break;
			
		case stopped:
			
		break;
		}
    }
}
